In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
%matplotlib inline

from scipy.stats import skew 

pd.set_option('display.max_columns', None)

In [3]:
TrData = pd.read_csv(r'C:\Users\PCAdmin\Desktop\Bootcamp\Train.csv')
TeData = pd.read_csv(r'C:\Users\PCAdmin\Desktop\Bootcamp\Test.csv')

In [4]:
TrData.head(5)

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,NaN,NaN,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,NaN,1052.0,8.0000,2.0,NaN,12.0,12.0,4.0,0.0,NaN,NaN,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,NaN,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,NaN,NaN,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,NaN,NaN,0.0,16576457,22452691.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1597.5,4746.0,3164.0,60.0,15696.0,NaN,14508.0,70.0,0.6666,0.0,NaN,12.0,0.0,6.0,0.0,149.6805,NaN,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,NaN,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,0.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,NaN,NaN,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,NaN,NaN,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,10326.45,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,5202.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,150.0135,NaN,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [19]:
TeData.head(5)

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,1649749.0,5446.0,0.0,48187375,114686147.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1086.0,6204.0,2676.0,60.0,14691.0,9794.0,NaN,238.0,1.8334,0.0,NaN,22.0,2.0,14.0,0.0,NaN,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,622789.0,1025793.0,1396510.0,34694910,87479487.0,1.0,1.0,1.0,2.0,2.0,142.560,NaN,NaN,570.585,3082.5,10221.0,6814.0,60.0,11955.0,3528.0,NaN,1216.0,19.5000,3.0,NaN,30.0,18.0,14.0,2.0,NaN,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,0.0,118256.0,NaN,NaN,21973443,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,852.0,4836.0,NaN,NaN,NaN,7.8334,0.0,NaN,2.0,NaN,0.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,1391064.0,1176725.0,1220293.0,16576457,NaN,2.0,2.0,2.0,3.0,3.0,109.005,13050.00,NaN,109.005,1414.5,4197.0,2798.0,60.0,14964.0,NaN,NaN,248.0,9.0000,1.0,1.0,36.0,0.0,26.0,0.0,NaN,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,271133.0,613064.0,4779643.0,48187375,72049802.0,0.0,0.0,0.0,3.0,3.0,139.065,469.29,469.29,15.180,2724.0,9855.0,6570.0,182.0,11679.0,5900.0,NaN,2388.0,16.6666,1.0,0.0,24.0,28.0,20.0,0.0,NaN,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [5]:
TrData.isnull().sum()

Applicant_ID          0
form_field1        2529
form_field2        3844
form_field3         355
form_field4         355
form_field5         355
form_field6       13360
form_field7        5163
form_field8       13360
form_field9        8008
form_field10        355
form_field11      31421
form_field12       9895
form_field13       5889
form_field14          0
form_field15      22475
form_field16      13036
form_field17      11151
form_field18      10402
form_field19          4
form_field20        355
form_field21      15854
form_field22      20400
form_field23      28123
form_field24      13297
form_field25       5450
form_field26       7438
form_field27       9299
form_field28        355
form_field29        355
form_field30      25509
form_field31      39408
form_field32       5450
form_field33       1256
form_field34        355
form_field35      23148
form_field36       1995
form_field37       5450
form_field38        355
form_field39       4211
form_field40      43729
form_field41      38229
form_field42       1323
form_field43        568
form_field44       5383
form_field45      31317
form_field46      15904
form_field47          0
form_field48      20889
form_field49        355
form_field50      11056
default_status        0
dtype: int64

In [6]:
numerical_features = [col for col in TrData.columns if TrData[col].dtypes != object]
categorical_features = [col for col in TrData.columns if TrData[col].dtypes == object]

In [31]:
numerical_cols = [col for col in TeData.columns if TeData[col].dtypes != object]
categorical_cols = [col for col in TeData.columns if TeData[col].dtypes == object]

In [32]:
print(categorical_cols)

['Applicant_ID', 'form_field47']

In [7]:
print(categorical_features)

['Applicant_ID', 'form_field47', 'default_status']

In [8]:
for col in TrData.columns:
    if TrData[col].isnull().any():
        percent_missing = TrData[col].isnull().sum() /(len(TrData[col])) *100 # Amount of missing value / Total length of dataset * 100
        print(f'{col}: {round(percent_missing, 2)}%')

form_field1: 4.52%
form_field2: 6.86%
form_field3: 0.63%
form_field4: 0.63%
form_field5: 0.63%
form_field6: 23.86%
form_field7: 9.22%
form_field8: 23.86%
form_field9: 14.3%
form_field10: 0.63%
form_field11: 56.11%
form_field12: 17.67%
form_field13: 10.52%
form_field15: 40.13%
form_field16: 23.28%
form_field17: 19.91%
form_field18: 18.58%
form_field19: 0.01%
form_field20: 0.63%
form_field21: 28.31%
form_field22: 36.43%
form_field23: 50.22%
form_field24: 23.74%
form_field25: 9.73%
form_field26: 13.28%
form_field27: 16.61%
form_field28: 0.63%
form_field29: 0.63%
form_field30: 45.55%
form_field31: 70.37%
form_field32: 9.73%
form_field33: 2.24%
form_field34: 0.63%
form_field35: 41.34%
form_field36: 3.56%
form_field37: 9.73%
form_field38: 0.63%
form_field39: 7.52%
form_field40: 78.09%
form_field41: 68.27%
form_field42: 2.36%
form_field43: 1.01%
form_field44: 9.61%
form_field45: 55.92%
form_field46: 28.4%
form_field48: 37.3%
form_field49: 0.63%
form_field50: 19.74%

In [26]:

#from sklearn.impute import SimpleImputer 
#imputer = SimpleImputer(fill_value= 0)
#TrData[numerical_features] = imputer.fit_transform(TrData[numerical_features])
TrData[numerical_features] = TrData[numerical_features].fillna(0)

In [27]:
TrData.isna().sum().any()

False

In [29]:
TeData = TeData.fillna(0)

In [30]:
TeData.isna().sum().any()

False

In [42]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

tran_f = ['default_status', 'form_field47']

for col in tran_f:
    TrData[col] = encoder.fit_transform(TrData[col])

In [43]:
TrData.head(5)

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,3436.0,0.28505,1.6560,0.0,0.000,0.000000,10689720.0,2.520720e+05,4272776.0,11333126.0,4.397256e+06,2.301324e+06,7875694.0,96375139.0,112181765.0,1.000000,1.000000,1.000000,3.0,3.0,134.65500,6628.316381,6452.875072,134.655000,4000.5,17064.0,11376.0,60.0,17064.0,5962.000000,10857.565755,1052.0,8.0000,2.0,0.199866,12.0,12.0,4.0,0.0,147.797977,108.117363,0.392854,2.02,0.711632,0.00000,0.0,0,305244.932775,1.129518,0.044335,0
1,3456.0,0.67400,0.2342,0.0,0.000,0.000000,898979.0,4.975310e+05,9073814.0,2533168.0,2.442920e+05,3.982971e+06,2141445.0,28141427.0,45169902.0,1.000000,1.000000,1.000000,2.0,2.0,109.23000,11385.240000,14584.290000,86.685000,4161.0,13413.0,8942.0,304.0,13413.0,5780.000000,10857.565755,2554.0,17.5000,0.0,0.000000,16.0,24.0,8.0,0.0,147.797977,108.117363,0.314281,8.08,0.183584,0.07252,0.0,0,349.805730,1.620483,0.322436,0
2,3276.0,0.53845,3.1510,0.0,6.282,624447.924437,956940.0,2.626690e+06,192944.0,1079864.0,2.054715e+06,2.771113e+06,0.0,16576457.0,22452691.0,0.230425,0.265692,0.271832,0.0,0.0,86.50038,6628.316381,6452.875072,104.558516,1597.5,4746.0,3164.0,60.0,15696.0,5213.246663,14508.000000,70.0,0.6666,0.0,0.199866,12.0,0.0,6.0,0.0,149.680500,108.117363,0.162965,18.18,0.791136,0.00000,0.0,0,305244.932775,1.513370,0.011640,1
3,3372.0,0.17005,0.5050,0.0,0.000,192166.000000,3044703.0,3.854990e+05,3986472.0,3621979.0,2.054715e+06,7.717760e+05,1186839.0,48187375.0,136297820.0,0.000000,0.000000,0.000000,1.0,1.0,120.12000,8580.000000,0.000000,85.800000,1701.0,4014.0,2676.0,60.0,11679.0,5213.246663,10857.565755,522.0,7.8334,1.0,1.000000,4.0,8.0,4.0,1.0,147.797977,108.117363,0.488884,2.02,0.685168,0.07252,0.0,0,89.940100,0.664452,0.082729,0
4,3370.0,0.77270,1.1010,0.0,0.000,1556.000000,214728.0,2.147280e+05,1284089.0,361770.0,3.963910e+05,8.184560e+05,511535.0,28141427.0,15292757.0,0.000000,0.000000,0.000000,3.0,3.0,104.53500,8360.190000,10326.450000,115.335000,1551.0,3285.0,2190.0,60.0,19437.0,12958.000000,5202.000000,272.0,1.0000,0.0,0.000000,24.0,2.0,24.0,0.0,150.013500,108.117363,0.275000,12.12,0.438168,0.00000,0.0,0,97.887502,1.427891,0.045630,0

In [44]:
TeData['form_field47'] = label_encoder.fit_transform(TeData['form_field47'])

TeData['form_field47'].unique()

array([0, 1])

In [45]:
TeData.head(5)

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,1649749.0,5446.0,0.0,48187375,114686147.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.00,0.000,1086.0,6204.0,2676.0,60.0,14691.0,9794.0,0.0,238.0,1.8334,0.0,0.0,22.0,2.0,14.0,0.0,0.0,0.0000,0.825000,1.01,0.800000,0.0,0.0,0,0.000000,0.000000,0.011221
1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,622789.0,1025793.0,1396510.0,34694910,87479487.0,1.0,1.0,1.0,2.0,2.0,142.560,0.00,0.00,570.585,3082.5,10221.0,6814.0,60.0,11955.0,3528.0,0.0,1216.0,19.5000,3.0,0.0,30.0,18.0,14.0,2.0,0.0,18.8415,0.507694,4.04,0.623248,1.0,0.0,1,0.000000,0.504974,0.043525
2,Apcnt_1000052,0.0,0.27505,0.0600,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,118256.0,0.0,0.0,21973443,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.00,0.000,0.0,0.0,0.0,852.0,4836.0,0.0,0.0,0.0,7.8334,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0000,0.000000,0.00,0.000000,0.0,0.0,0,0.000000,0.000000,0.000000
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,1391064.0,1176725.0,1220293.0,16576457,0.0,2.0,2.0,2.0,3.0,3.0,109.005,13050.00,0.00,109.005,1414.5,4197.0,2798.0,60.0,14964.0,0.0,0.0,248.0,9.0000,1.0,1.0,36.0,0.0,26.0,0.0,0.0,0.0000,0.916663,2.02,0.464224,0.0,0.0,0,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,271133.0,613064.0,4779643.0,48187375,72049802.0,0.0,0.0,0.0,3.0,3.0,139.065,469.29,469.29,15.180,2724.0,9855.0,6570.0,182.0,11679.0,5900.0,0.0,2388.0,16.6666,1.0,0.0,24.0,28.0,20.0,0.0,0.0,0.0000,0.234047,23.23,0.726688,0.0,0.0,1,1303.587148,1.637733,0.163124

In [77]:
feature_names = ['form_field1', 'form_field2',  'form_field3', 'form_field7', 'form_field10', 'form_field12',  'form_field14', 'form_field16', 'form_field18', 'form_field20', 'form_field21', 'form_field23', 'form_field24', 'form_field26', 'form_field27', 'form_field28', 'form_field29', 'form_field30', 'form_field31', 'form_field33', 'form_field34', 'form_field36', 'form_field38', 'form_field39', 'form_field40', 'form_field41', 'form_field42', 'form_field43', 'form_field44', 'form_field47', 'form_field50']
X = TrData[feature_names]

In [78]:
y = TrData['default_status']

In [76]:
feature_name = ['form_field1', 'form_field2',  'form_field3', 'form_field7', 'form_field10', 'form_field12',  'form_field14', 'form_field16', 'form_field18', 'form_field20', 'form_field21', 'form_field23', 'form_field24', 'form_field26', 'form_field27', 'form_field28', 'form_field29', 'form_field30', 'form_field31', 'form_field33', 'form_field34', 'form_field36', 'form_field38', 'form_field39', 'form_field40', 'form_field41', 'form_field42', 'form_field43', 'form_field44', 'form_field47', 'form_field50']
X_test = TeData[feature_name]

In [79]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler

In [80]:
X, y = load_iris(return_X_y=True)
print(X.shape)

(150, 4)

In [81]:
scaler = MinMaxScaler()
scaler.fit(X)

MinMaxScaler()

In [82]:
X_scaled = scaler.transform(X)

In [83]:
X_scaled.min(axis=0)

array([0., 0., 0., 0.])

In [84]:
X_scaled.max(axis=0)

array([1., 1., 1., 1.])

In [85]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

In [86]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

RandomForestClassifier()

In [87]:
clf.score(X, y)

0.9866666666666667

In [89]:
y_predicted = clf.predict_proba(X_test)[:, 1]

ValueError: Number of features of the model must match the input. Model n_features is 4 and input n_features is 31